require("prototypes.debug")
require("prototypes.category")
require("prototypes.equipment")
require("prototypes.item")
require("prototypes.recipe")
require("prototypes.entity")
require("prototypes.technology")
