data:extend({
	{
		type = "item",
		name = "logicarts-car",
		icon = "__logicarts__/graphics/cart-ico.png",
		icon_size = 32,
		flags = {"goes-to-quickbar"},
		place_result = "logicarts-car",
		order = "logicarts-a-a",
		stack_size = 50,
	},
	{
		type = "item",
		name = "logicarts-car-electric",
		icon = "__logicarts__/graphics/e-cart-ico.png",
		icon_size = 32,
		flags = {"goes-to-quickbar"},
		place_result = "logicarts-car-electric",
		order = "logicarts-a-a",
		stack_size = 50,
	},
	{
		type = "item",
		name = "logicarts-path",
		icon = "__logicarts__/path-icon.png",
		icon_size = 128,
		flags = {"goes-to-quickbar"},
		place_result = "logicarts-path",
		order = "logicarts-a-b",
		stack_size = 200,
	},
	{
		type = "item",
		name = "logicarts-path-north",
		icon = "__logicarts__/path-icon.png",
		icon_size = 128,
		flags = {"hidden"},
		order = "logicarts-a",
		stack_size = 200,
	},
	{
		type = "item",
		name = "logicarts-path-east",
		icon = "__logicarts__/path-icon.png",
		icon_size = 128,
		flags = {"hidden"},
		order = "logicarts-a",
		stack_size = 200,
	},
	{
		type = "item",
		name = "logicarts-path-south",
		icon = "__logicarts__/path-icon.png",
		icon_size = 128,
		flags = {"hidden"},
		order = "logicarts-a",
		stack_size = 200,
	},
	{
		type = "item",
		name = "logicarts-path-west",
		icon = "__logicarts__/path-icon.png",
		icon_size = 128,
		flags = {"hidden"},
		order = "logicarts-a",
		stack_size = 200,
	},
	{
		type = "item",
		name = "logicarts-turn",
		icon = "__logicarts__/turn-icon.png",
		icon_size = 128,
		flags = {"goes-to-quickbar"},
		place_result = "logicarts-turn",
		order = "logicarts-a-c",
		stack_size = 200,
	},
	{
		type = "item",
		name = "logicarts-turn-north",
		icon = "__logicarts__/turn-icon.png",
		icon_size = 128,
		flags = {"hidden"},
		order = "logicarts-a",
		stack_size = 200,
	},
	{
		type = "item",
		name = "logicarts-turn-east",
		icon = "__logicarts__/turn-icon.png",
		icon_size = 128,
		flags = {"hidden"},
		order = "logicarts-a",
		stack_size = 200,
	},
	{
		type = "item",
		name = "logicarts-turn-south",
		icon = "__logicarts__/turn-icon.png",
		icon_size = 128,
		flags = {"hidden"},
		order = "logicarts-a",
		stack_size = 200,
	},
	{
		type = "item",
		name = "logicarts-turn-west",
		icon = "__logicarts__/turn-icon.png",
		icon_size = 128,
		flags = {"hidden"},
		order = "logicarts-a",
		stack_size = 200,
	},
	{
		type = "item",
		name = "logicarts-stop",
		icon = "__logicarts__/stop-icon.png",
		icon_size = 128,
		flags = {"goes-to-quickbar"},
		place_result = "logicarts-stop",
		order = "logicarts-a-c",
		stack_size = 200,
	},
	{
		type = "item",
		name = "logicarts-stop-north",
		icon = "__logicarts__/stop-icon.png",
		icon_size = 128,
		flags = {"hidden"},
		order = "logicarts-a",
		stack_size = 200,
	},
	{
		type = "item",
		name = "logicarts-stop-east",
		icon = "__logicarts__/stop-icon.png",
		icon_size = 128,
		flags = {"hidden"},
		order = "logicarts-a",
		stack_size = 200,
	},
	{
		type = "item",
		name = "logicarts-stop-south",
		icon = "__logicarts__/stop-icon.png",
		icon_size = 128,
		flags = {"hidden"},
		order = "logicarts-a",
		stack_size = 200,
	},
	{
		type = "item",
		name = "logicarts-stop-west",
		icon = "__logicarts__/stop-icon.png",
		icon_size = 128,
		flags = {"hidden"},
		order = "logicarts-a",
		stack_size = 200,
	},
	{
		type = "item",
		name = "logicarts-yield",
		icon = "__logicarts__/yield-icon.png",
		icon_size = 128,
		flags = {"goes-to-quickbar"},
		place_result = "logicarts-yield",
		order = "logicarts-a-c",
		stack_size = 200,
	},
	{
		type = "item",
		name = "logicarts-marker",
		icon = "__logicarts__/nothing.png",
		icon_size = 32,
		flags = {"goes-to-quickbar"},
		place_result = "logicarts-marker",
		order = "logicarts-z",
		stack_size = 200,
	},
	-- turn-blocked
	{
		type = "item",
		name = "logicarts-turn-blocked",
		icon = "__logicarts__/turn-blocked-icon.png",
		icon_size = 128,
		flags = {"goes-to-quickbar"},
		place_result = "logicarts-turn-blocked",
		order = "logicarts-a-c",
		stack_size = 200,
	},
	{
		type = "item",
		name = "logicarts-turn-blocked-north",
		icon = "__logicarts__/turn-blocked-icon.png",
		icon_size = 128,
		flags = {"hidden"},
		order = "logicarts-a",
		stack_size = 200,
	},
	{
		type = "item",
		name = "logicarts-turn-blocked-east",
		icon = "__logicarts__/turn-blocked-icon.png",
		icon_size = 128,
		flags = {"hidden"},
		order = "logicarts-a",
		stack_size = 200,
	},
	{
		type = "item",
		name = "logicarts-turn-blocked-south",
		icon = "__logicarts__/turn-blocked-icon.png",
		icon_size = 128,
		flags = {"hidden"},
		order = "logicarts-a",
		stack_size = 200,
	},
	{
		type = "item",
		name = "logicarts-turn-blocked-west",
		icon = "__logicarts__/turn-blocked-icon.png",
		icon_size = 128,
		flags = {"hidden"},
		order = "logicarts-a",
		stack_size = 200,
	},
})
