data:extend({
	{
		type = "item",
		name = "logicarts-car",
		icon = "__logicarts__/graphics/cart-ico.png",
		icon_size = 32,
		flags = {"goes-to-quickbar"},
		place_result = "logicarts-car",
		order = "logicarts-a-a",
		stack_size = 50,
		subgroup = "logicarts-subgroup",
	},
	{
		type = "item",
		name = "logicarts-car-electric",
		icon = "__logicarts__/graphics/e-cart-ico.png",
		icon_size = 32,
		flags = {"goes-to-quickbar"},
		place_result = "logicarts-car-electric",
		order = "logicarts-a-a",
		stack_size = 50,
		subgroup = "logicarts-subgroup",
	},
	{
		type = "item",
		name = "logicarts-paint",
		icon = "__logicarts__/paint-icon.png",
		icon_size = 128,
		flags = {"goes-to-quickbar"},
		order = "logicarts-a-a",
		stack_size = 50,
		subgroup = "logicarts-subgroup",
	},
	{
		type = "item",
		name = "logicarts-path",
		icon = "__logicarts__/path-icon.png",
		icon_size = 128,
		flags = {"goes-to-quickbar"},
		place_result = "logicarts-path",
		order = "logicarts-a-b",
		stack_size = 200,
		subgroup = "logicarts-subgroup-path",
	},
	{
		type = "item",
		name = "logicarts-path-north",
		icon = "__logicarts__/path-icon.png",
		icon_size = 128,
		flags = {"hidden"},
		order = "logicarts-a",
		stack_size = 200,
	},
	{
		type = "item",
		name = "logicarts-path-east",
		icon = "__logicarts__/path-icon.png",
		icon_size = 128,
		flags = {"hidden"},
		order = "logicarts-a",
		stack_size = 200,
	},
	{
		type = "item",
		name = "logicarts-path-south",
		icon = "__logicarts__/path-icon.png",
		icon_size = 128,
		flags = {"hidden"},
		order = "logicarts-a",
		stack_size = 200,
	},
	{
		type = "item",
		name = "logicarts-path-west",
		icon = "__logicarts__/path-icon.png",
		icon_size = 128,
		flags = {"hidden"},
		order = "logicarts-a",
		stack_size = 200,
	},
	{
		type = "item",
		name = "logicarts-turn",
		icon = "__logicarts__/turn-icon.png",
		icon_size = 128,
		flags = {"goes-to-quickbar"},
		place_result = "logicarts-turn",
		order = "logicarts-a-c",
		stack_size = 200,
		subgroup = "logicarts-subgroup-path",
	},
	{
		type = "item",
		name = "logicarts-turn-north",
		icon = "__logicarts__/turn-icon.png",
		icon_size = 128,
		flags = {"hidden"},
		order = "logicarts-a",
		stack_size = 200,
	},
	{
		type = "item",
		name = "logicarts-turn-east",
		icon = "__logicarts__/turn-icon.png",
		icon_size = 128,
		flags = {"hidden"},
		order = "logicarts-a",
		stack_size = 200,
	},
	{
		type = "item",
		name = "logicarts-turn-south",
		icon = "__logicarts__/turn-icon.png",
		icon_size = 128,
		flags = {"hidden"},
		order = "logicarts-a",
		stack_size = 200,
	},
	{
		type = "item",
		name = "logicarts-turn-west",
		icon = "__logicarts__/turn-icon.png",
		icon_size = 128,
		flags = {"hidden"},
		order = "logicarts-a",
		stack_size = 200,
	},
	{
		type = "item",
		name = "logicarts-stop",
		icon = "__logicarts__/stop-icon.png",
		icon_size = 128,
		flags = {"goes-to-quickbar"},
		place_result = "logicarts-stop",
		order = "logicarts-a-c",
		stack_size = 200,
		subgroup = "logicarts-subgroup-path",
	},
	{
		type = "item",
		name = "logicarts-stop-north",
		icon = "__logicarts__/stop-icon.png",
		icon_size = 128,
		flags = {"hidden"},
		order = "logicarts-a",
		stack_size = 200,
	},
	{
		type = "item",
		name = "logicarts-stop-east",
		icon = "__logicarts__/stop-icon.png",
		icon_size = 128,
		flags = {"hidden"},
		order = "logicarts-a",
		stack_size = 200,
	},
	{
		type = "item",
		name = "logicarts-stop-south",
		icon = "__logicarts__/stop-icon.png",
		icon_size = 128,
		flags = {"hidden"},
		order = "logicarts-a",
		stack_size = 200,
	},
	{
		type = "item",
		name = "logicarts-stop-west",
		icon = "__logicarts__/stop-icon.png",
		icon_size = 128,
		flags = {"hidden"},
		order = "logicarts-a",
		stack_size = 200,
	},
	{
		type = "item",
		name = "logicarts-yield",
		icon = "__logicarts__/yield-icon.png",
		icon_size = 128,
		flags = {"goes-to-quickbar"},
		place_result = "logicarts-yield",
		order = "logicarts-a-c",
		stack_size = 200,
		subgroup = "logicarts-subgroup-path",
	},
	{
		type = "item",
		name = "logicarts-marker",
		icon = "__logicarts__/nothing.png",
		icon_size = 32,
		flags = {"hidden"},
		place_result = "logicarts-marker",
		order = "logicarts-z",
		stack_size = 200,
	},
	-- turn-blocked
	{
		type = "item",
		name = "logicarts-turn-blocked",
		icon = "__logicarts__/turn-blocked-icon.png",
		icon_size = 128,
		flags = {"goes-to-quickbar"},
		place_result = "logicarts-turn-blocked",
		order = "logicarts-a-c",
		stack_size = 200,
		subgroup = "logicarts-subgroup-path",
	},
	{
		type = "item",
		name = "logicarts-turn-blocked-north",
		icon = "__logicarts__/turn-blocked-icon.png",
		icon_size = 128,
		flags = {"hidden"},
		order = "logicarts-a",
		stack_size = 200,
	},
	{
		type = "item",
		name = "logicarts-turn-blocked-east",
		icon = "__logicarts__/turn-blocked-icon.png",
		icon_size = 128,
		flags = {"hidden"},
		order = "logicarts-a",
		stack_size = 200,
	},
	{
		type = "item",
		name = "logicarts-turn-blocked-south",
		icon = "__logicarts__/turn-blocked-icon.png",
		icon_size = 128,
		flags = {"hidden"},
		order = "logicarts-a",
		stack_size = 200,
	},
	{
		type = "item",
		name = "logicarts-turn-blocked-west",
		icon = "__logicarts__/turn-blocked-icon.png",
		icon_size = 128,
		flags = {"hidden"},
		order = "logicarts-a",
		stack_size = 200,
	},
	{
		type = "item",
		name = "logicarts-continue",
		icon = "__logicarts__/continue-icon.png",
		icon_size = 128,
		flags = {"goes-to-quickbar"},
		place_result = "logicarts-continue",
		order = "logicarts-a-b",
		stack_size = 200,
		subgroup = "logicarts-subgroup-path",
	},
	{
		type = "item",
		name = "logicarts-continue-north",
		icon = "__logicarts__/continue-icon.png",
		icon_size = 128,
		flags = {"hidden"},
		order = "logicarts-a",
		stack_size = 200,
	},
	{
		type = "item",
		name = "logicarts-continue-east",
		icon = "__logicarts__/continue-icon.png",
		icon_size = 128,
		flags = {"hidden"},
		order = "logicarts-a",
		stack_size = 200,
	},
	{
		type = "item",
		name = "logicarts-continue-south",
		icon = "__logicarts__/continue-icon.png",
		icon_size = 128,
		flags = {"hidden"},
		order = "logicarts-a",
		stack_size = 200,
	},
	{
		type = "item",
		name = "logicarts-continue-west",
		icon = "__logicarts__/continue-icon.png",
		icon_size = 128,
		flags = {"hidden"},
		order = "logicarts-a",
		stack_size = 200,
	},
	{
		type = "item",
		name = "logicarts-turn-fuel",
		icon = "__logicarts__/turn-fuel-icon.png",
		icon_size = 128,
		flags = {"goes-to-quickbar"},
		place_result = "logicarts-turn-fuel",
		order = "logicarts-a-b",
		stack_size = 200,
		subgroup = "logicarts-subgroup-path",
	},
	{
		type = "item",
		name = "logicarts-turn-fuel-north",
		icon = "__logicarts__/turn-fuel-icon.png",
		icon_size = 128,
		flags = {"hidden"},
		order = "logicarts-a",
		stack_size = 200,
	},
	{
		type = "item",
		name = "logicarts-turn-fuel-east",
		icon = "__logicarts__/turn-fuel-icon.png",
		icon_size = 128,
		flags = {"hidden"},
		order = "logicarts-a",
		stack_size = 200,
	},
	{
		type = "item",
		name = "logicarts-turn-fuel-south",
		icon = "__logicarts__/turn-fuel-icon.png",
		icon_size = 128,
		flags = {"hidden"},
		order = "logicarts-a",
		stack_size = 200,
	},
	{
		type = "item",
		name = "logicarts-turn-fuel-west",
		icon = "__logicarts__/turn-fuel-icon.png",
		icon_size = 128,
		flags = {"hidden"},
		order = "logicarts-a",
		stack_size = 200,
	},
})

local function groupTile(t, n, d)
	return {
		type = "item",
		name = "logicarts-"..t.."-G"..n.."-"..d,
		icon = "__logicarts__/"..t.."-G"..n.."-icon.png",
		icon_size = 128,
		flags = {"hidden"},
		order = "logicarts-a-"..n,
		stack_size = 200,
	}
end

local function groupTiles(t, n)
	data:extend({
		{
			type = "item",
			name = "logicarts-"..t.."-G"..n,
			icon = "__logicarts__/"..t.."-G"..n.."-icon.png",
			icon_size = 128,
			flags = {"goes-to-quickbar"},
			place_result = "logicarts-"..t.."-G"..n,
			order = "logicarts-a-c",
			stack_size = 200,
			subgroup = "logicarts-subgroup-signal-"..t,
		},
		groupTile(t, n, "north"),
		groupTile(t, n, "south"),
		groupTile(t, n, "east"),
		groupTile(t, n, "west"),
	})
end

groupTiles("path", 1)
groupTiles("path", 2)
groupTiles("path", 3)
groupTiles("path", 4)
groupTiles("path", 5)

groupTiles("turn", 1)
groupTiles("turn", 2)
groupTiles("turn", 3)
groupTiles("turn", 4)
groupTiles("turn", 5)