data:extend({
	{
		type = "recipe",
		name = "logicarts-car",
		category = "crafting",
		subgroup = "logicarts-subgroup",
		enabled = false,
		icon = "__logicarts__/graphics/cart-ico.png",
		icon_size = 32,
		ingredients = {
			{ type = "item", name = "engine-unit", amount = 2 },
			{ type = "item", name = "steel-plate", amount = 4 },
			{ type = "item", name = "electronic-circuit", amount = 4 },
		},
		results = {
			{ type = "item", name = "logicarts-car", amount = 1 },
		},
		hidden = false,
		energy_required = 5.0,
		order = "logicarts-a",
	},
	{
		type = "recipe",
		name = "logicarts-car-electric",
		category = "crafting",
		subgroup = "logicarts-subgroup",
		enabled = false,
		icon = "__logicarts__/graphics/e-cart-ico.png",
		icon_size = 32,
		ingredients = {
			{ type = "item", name = "electric-engine-unit", amount = 2 },
			{ type = "item", name = "steel-plate", amount = 4 },
			{ type = "item", name = "advanced-circuit", amount = 4 },
		},
		results = {
			{ type = "item", name = "logicarts-car-electric", amount = 1 },
		},
		hidden = false,
		energy_required = 5.0,
		order = "logicarts-b",
	},
	{
		type = "recipe",
		name = "logicarts-path",
		category = "crafting-with-fluid",
		subgroup = "logicarts-subgroup-path",
		enabled = false,
		icon = "__logicarts__/path-icon.png",
		icon_size = 128,
		ingredients = {
			{ type = "item", name = "copper-ore", amount = 1 },
			{ type = "fluid", name = "water", amount = 10 },
		},
		results = {
			{ type = "item", name = "logicarts-path", amount = 10 },
		},
		hidden = false,
		energy_required = 1.0,
		order = "logicarts-a",
	},
	{
		type = "recipe",
		name = "logicarts-stop",
		category = "crafting-with-fluid",
		subgroup = "logicarts-subgroup-path",
		enabled = false,
		icon = "__logicarts__/stop-icon.png",
		icon_size = 128,
		ingredients = {
			{ type = "item", name = "copper-ore", amount = 1 },
			{ type = "fluid", name = "water", amount = 10 },
		},
		results = {
			{ type = "item", name = "logicarts-stop", amount = 10 },
		},
		hidden = false,
		energy_required = 1.0,
		order = "logicarts-b",
	},
	{
		type = "recipe",
		name = "logicarts-turn",
		category = "crafting-with-fluid",
		subgroup = "logicarts-subgroup-path",
		enabled = false,
		icon = "__logicarts__/turn-icon.png",
		icon_size = 128,
		ingredients = {
			{ type = "item", name = "iron-ore", amount = 1 },
			{ type = "fluid", name = "water", amount = 10 },
		},
		results = {
			{ type = "item", name = "logicarts-turn", amount = 10 },
		},
		hidden = false,
		energy_required = 1.0,
		order = "logicarts-c",
	},
	{
		type = "recipe",
		name = "logicarts-turn-blocked",
		category = "crafting-with-fluid",
		subgroup = "logicarts-subgroup-path",
		enabled = false,
		icon = "__logicarts__/turn-blocked-icon.png",
		icon_size = 128,
		ingredients = {
			{ type = "item", name = "copper-ore", amount = 1 },
			{ type = "fluid", name = "water", amount = 10 },
		},
		results = {
			{ type = "item", name = "logicarts-turn-blocked", amount = 10 },
		},
		hidden = false,
		energy_required = 1.0,
		order = "logicarts-d",
	},
	{
		type = "recipe",
		name = "logicarts-continue",
		category = "crafting-with-fluid",
		subgroup = "logicarts-subgroup-path",
		enabled = false,
		icon = "__logicarts__/continue-icon.png",
		icon_size = 128,
		ingredients = {
			{ type = "item", name = "copper-ore", amount = 1 },
			{ type = "fluid", name = "water", amount = 10 },
		},
		results = {
			{ type = "item", name = "logicarts-continue", amount = 10 },
		},
		hidden = false,
		energy_required = 1.0,
		order = "logicarts-e",
	},
	{
		type = "recipe",
		name = "logicarts-yield",
		category = "crafting-with-fluid",
		subgroup = "logicarts-subgroup-path",
		enabled = false,
		icon = "__logicarts__/yield-icon.png",
		icon_size = 128,
		ingredients = {
			{ type = "item", name = "iron-ore", amount = 1 },
			{ type = "fluid", name = "water", amount = 10 },
		},
		results = {
			{ type = "item", name = "logicarts-yield", amount = 10 },
		},
		hidden = false,
		energy_required = 1.0,
		order = "logicarts-e",
	},
})

local function tileGroup(t, n)
	return {
		type = "recipe",
		name = "logicarts-"..t.."-G"..n,
		category = "crafting",
		subgroup = "logicarts-subgroup-signal-"..t.."",
		enabled = false,
		icon = "__logicarts__/"..t.."-G"..n.."-icon.png",
		icon_size = 128,
		ingredients = {
			{ type = "item", name = "logicarts-"..t, amount = 1 },
			{ type = "item", name = "iron-plate",     amount = 1 },
		},
		results = {
			{ type = "item", name = "logicarts-"..t.."-G"..n, amount = 10 },
		},
		hidden = false,
		energy_required = 1.0,
		order = "logicarts-a-"..n,
	}
end

data:extend({
	tileGroup("path", 1),
	tileGroup("path", 2),
	tileGroup("path", 3),
	tileGroup("path", 4),
	tileGroup("path", 5),
	tileGroup("turn", 1),
	tileGroup("turn", 2),
	tileGroup("turn", 3),
	tileGroup("turn", 4),
	tileGroup("turn", 5),
})