data:extend({
	{
	  type = "recipe",
	  name = "logicarts-path",
	  category = "crafting-with-fluid",
    subgroup = "logicarts-subgroup",
	  enabled = false,
	  icon = "__logicarts__/path-icon.png",
	  icon_size = 128,
	  ingredients = {
	    { type = "item", name = "copper-ore", amount = 1 },
	    { type = "fluid", name = "water", amount = 10 },
	  },
	  results = {
	    { type = "item", name = "logicarts-path", amount = 10 },
	  },
	  hidden = false,
	  energy_required = 1.0,
	  order = "logicarts-a-b",
	},
  {
    type = "recipe",
    name = "logicarts-turn",
    category = "crafting-with-fluid",
    subgroup = "logicarts-subgroup",
    enabled = false,
    icon = "__logicarts__/turn-icon.png",
    icon_size = 128,
    ingredients = {
      { type = "item", name = "iron-ore", amount = 1 },
      { type = "fluid", name = "water", amount = 10 },
    },
    results = {
      { type = "item", name = "logicarts-turn", amount = 10 },
    },
    hidden = false,
    energy_required = 1.0,
    order = "logicarts-a-c",
  },
  {
    type = "recipe",
    name = "logicarts-stop",
    category = "crafting-with-fluid",
    subgroup = "logicarts-subgroup",
    enabled = false,
    icon = "__logicarts__/stop-icon.png",
    icon_size = 128,
    ingredients = {
      { type = "item", name = "copper-ore", amount = 1 },
      { type = "fluid", name = "water", amount = 10 },
    },
    results = {
      { type = "item", name = "logicarts-stop", amount = 10 },
    },
    hidden = false,
    energy_required = 1.0,
    order = "logicarts-a-e",
  },
  {
    type = "recipe",
    name = "logicarts-yield",
    category = "crafting-with-fluid",
    subgroup = "logicarts-subgroup",
    enabled = false,
    icon = "__logicarts__/yield-icon.png",
    icon_size = 128,
    ingredients = {
      { type = "item", name = "iron-ore", amount = 1 },
      { type = "fluid", name = "water", amount = 10 },
    },
    results = {
      { type = "item", name = "logicarts-yield", amount = 10 },
    },
    hidden = false,
    energy_required = 1.0,
    order = "logicarts-a-d",
  },
	{
	  type = "recipe",
	  name = "logicarts-car",
	  category = "advanced-crafting",
    subgroup = "logicarts-subgroup",
	  enabled = false,
	  icon = "__logicarts__/car-icon.png",
	  icon_size = 128,
	  ingredients = {
      { type = "item", name = "engine-unit", amount = 1 },
      { type = "item", name = "steel-plate", amount = 1 },
      { type = "item", name = "electronic-circuit", amount = 1 },
	  },
	  results = {
	    { type = "item", name = "logicarts-car", amount = 1 },
	  },
	  hidden = false,
	  energy_required = 2.0,
	  order = "logicarts-a-a",
	},
})
